# Generated by Django 5.0.6 on 2024-09-19 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Despedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField()),
                ('fecha', models.DateField(verbose_name='Fecha Despido')),
                ('pagado', models.BooleanField(verbose_name='Todo Al Día')),
            ],
        ),
        migrations.CreateModel(
            name='Postulante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('codigo', models.IntegerField(blank=True, null=True, verbose_name='Codigo Postal')),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('realiza', models.CharField(max_length=30, verbose_name='Desenpeña')),
                ('numero', models.BigIntegerField()),
                ('tfn', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
    ]
